os: osx
language: r
latex: false
pandoc: false
fortran: false
disable_homebrew: true
sudo: required

matrix:
  include:
    - osx_image: xcode11.3
    - osx_image: xcode10.1
    - osx_image: xcode7.3
      r: 3.6.3
      before_script:
        - sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

before_install:
  - sudo networksetup -setdnsservers Ethernet 1.1.1.1
  - sudo chmod 400 ~/Library/Logs ~/Library/Caches
  - sudo cat /usr/lib/pkgconfig/libpq.pc | sed 's|.Internal||g' | sed 's|/local||g' > /usr/local/lib/pkgconfig/libpq.pc
  - git config --global protocol.version 1

install:
  R -e 'install.packages("gh")'

script:
  - mkdir fakehome
  - cp ~/.gitconfig fakehome/ || touch fakehome/.gitconfig
  - chmod 500 fakehome
  - HOME="$PWD/fakehome" Rscript testcran.R

